name: 'Create, Approve, and Merge Version Bump PR'
description: 'Creates a version bump pull request, approves it, and merges it automatically'

inputs:
  # Required inputs
  repository:
    description: 'Target repository (e.g., "pattern-labs/maps")'
    required: true
  commit-message:
    description: 'Commit message for the changes'
    required: true
  title:
    description: 'Pull request title'
    required: true
  add-paths:
    description: 'Files to add to the commit (space or newline separated)'
    required: true

  # Token inputs (required for composite actions)
  repo-access-token:
    description: 'Token with repo access for creating and merging PRs'
    required: true
  pr-approver-token:
    description: 'Token for approving the pull request'
    required: true

  # Optional inputs with defaults
  body:
    description: 'Pull request body/description'
    required: false
    default: 'Automated PR created by reusable action'
  branch:
    description: 'Branch name for the pull request'
    required: false
    default: 'automation/${{ github.run_id }}'
  path:
    description: 'Working directory path'
    required: false
    default: '.'
  delete-branch:
    description: 'Whether to delete the branch after merge'
    required: false
    default: 'true'
  merge-method:
    description: 'Merge method (squash, merge, or rebase)'
    required: false
    default: 'squash'

outputs:
  pull-request-number:
    description: 'The number of the created pull request'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pull-request-url:
    description: 'The URL of the created pull request'
    value: ${{ steps.create-pr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.repo-access-token }}
        path: ${{ inputs.path }}
        commit-message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
        title: ${{ inputs.title }}
        add-paths: ${{ inputs.add-paths }}
        body: ${{ inputs.body }}
        delete-branch: ${{ inputs.delete-branch }}

    - name: Approve Pull Request
      if: steps.create-pr.outputs.pull-request-number != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pr-approver-token }}
      run: |
        gh pr review \
          --repo "${{ inputs.repository }}" \
          "${{ steps.create-pr.outputs.pull-request-number }}" \
          --approve

    - name: Merge Pull Request
      if: steps.create-pr.outputs.pull-request-number != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-access-token }}
      run: |
        gh pr merge \
          --repo "${{ inputs.repository }}" \
          "${{ steps.create-pr.outputs.pull-request-number }}" \
          --${{ inputs.merge-method }} \
          --auto
