name: 'Pattern Cloud Setup'
description: 'Boilerplate for all Pattern Cloud Workflows'

inputs:
  docker_user:
    description: 'Docker Hub username'
    required: true
    type: string
  docker_password:
    description: 'Docker Hub password'
    required: true
    type: string
  helm_user:
    description: 'Harbor Registry username'
    required: true
    type: string
  helm_password:
    description: 'Harbor Registry password'
    required: true
    type: string
  repo_access_pat:
    description: 'GitHub Personal Access Token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_user }}
        password: ${{ inputs.docker_password }}

    - name: Install Helm
      uses: Azure/setup-helm@v3

    - name: Log in to Harbor Registry
      run: |
        echo '${{ inputs.helm_password }}' | helm registry login harbor.rutherford.patternlabs.tech -u '${{ inputs.helm_user }}' --password-stdin

    - name: Setup .netrc
      uses: Pattern-Labs/.github/.github/actions/setup_netrc.yml@v1
      with:
        repo_access_pat: ${{ inputs.repo_access_pat }}

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        project_id: "stalwart-summer-374519"
        workload_identity_provider: "projects/515604670361/locations/global/workloadIdentityPools/github/providers/pattern"
        service_account: "github-runner@stalwart-summer-374519.iam.gserviceaccount.com"

    - name: Install the Pattern CLI
      uses: Pattern-Labs/.github/.github/actions/pattern_cli.yml@v1

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        lfs: true