name: 'GKE Cloud Auth Setup'
description: 'Setup GKE Cloud Auth'
runs:
  using: "composite"
  steps:
    - name: Setup Google Cloud SDK apt keys
      shell: bash
      run: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: Apt Update
      shell: bash
      run: sudo apt-get update -y

    - name: Install gke-gcloud-auth-plugin
      shell: bash
      run: |
        sudo apt install -y \
        google-cloud-sdk-gke-gcloud-auth-plugin
