# TODO(lou): currently the only differences between this action and setup_cloud_deps_base
#            are the default values for what all it does. Does anything break if we set
#            all of the defaults to true and by default install everything?
name: "Cloud Dependencies Setup"
description: "Installs the various cloud dependencies needed for the build and deploy workflows."
inputs:
  repo_access_pat:
    description: "GitHub Personal Access Token"
    required: true
  docker_user:
    description: "Docker Hub Username"
    required: true
  docker_password:
    description: "Docker Hub Password"
    required: true
  helm_user:
    description: "Harbor Registry Username"
    required: true
  helm_password:
    description: "Harbor Registry Password"
    required: true
  helm_version:
    description: "Helm version to install"
    required: false
    # latest version at the time. v4 has breaking changes, will
    # need to test before upgrading
    default: "v3.19.4"
  setup_pattern_cli:
    description: "Whether to setup the Pattern CLI."
    required: false
    default: true
  pattern_cli_add_to_usr_bin:
    description: "If true, copies the Pattern CLI to /usr/bin"
    required: false
    default: "true"
  pattern_cli_version:
    description: "Pattern CLI version to install (tag, latest, or branch name)"
    required: false
    default: "latest"
  setup_gke_cloud_auth:
    description: "If true, sets up Google Cloud SDK auth plugin"
    required: false
    default: "true"
  setup_bazel:
    description: "If true, sets up Bazel"
    required: false
    default: "true"
  setup_docker_cli:
    description: "If true, sets up Docker CLI"
    required: false
    default: "false"
  setup_kubectx:
    description: "If true, sets up kubectx"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_user }}
        password: ${{ inputs.docker_password }}

    - name: Install Helm
      uses: Azure/setup-helm@v4.3.1
      with:
        version: ${{ inputs.helm_version }}

    - name: Log in to Harbor Registry
      shell: bash
      run: |
        echo '${{ inputs.helm_password }}' | helm registry login harbor.rutherford.patternlabs.tech -u '${{ inputs.helm_user }}' --password-stdin

    - name: Setup .netrc
      uses: Pattern-Labs/.github/.github/actions/setup_netrc@main
      with:
        repo_access_pat: ${{ inputs.repo_access_pat }}

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4

    - name: Install the Pattern CLI
      if: ${{ inputs.setup_pattern_cli == 'true' }}
      uses: ./.github/actions/pattern_cli
      with:
        add_to_usr_bin: ${{ inputs.pattern_cli_add_to_usr_bin }}
        version: ${{ inputs.pattern_cli_version }}

    - name: Setup GKE GCloud Auth
      if: ${{ inputs.setup_gke_cloud_auth == 'true' }}
      uses: Pattern-Labs/.github/.github/actions/gke_cloud_auth@main

    - name: Setup Bazel
      if: ${{ inputs.setup_bazel == 'true' }}
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Install kubectx
      if: ${{ inputs.setup_kubectx == 'true' }}
      shell: bash
      working-directory: /tmp
      run: |
        if ! which kubectx > /dev/null 2>&1; then
          if [ ! -d "kubectx" ]; then
            git clone https://github.com/ahmetb/kubectx
          fi
          echo "/tmp/kubectx" >> $GITHUB_PATH
        fi
