name: 'Cloud Dependencies Setup'
description: 'Installs the various cloud dependencies needed for the build and deploy workflows.'
inputs:
  repo_access_pat:
    description: 'GitHub Personal Access Token'
    required: true
    type: string
  docker_user:
    description: 'Docker Hub Username'
    required: true
    type: string
  docker_password:
    description: 'Docker Hub Password'
    required: true
    type: string
  helm_user:
    description: 'Harbor Registry Username'
    required: true
    type: string
  helm_password:
    description: 'Harbor Registry Password'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup Cloud Deps Base
      uses: Pattern-Labs/.github/.github/actions/setup_netrc@main
      with:
        repo_access_pat: ${{ inputs.repo_access_pat }}
        docker_user: ${{ inputs.docker_user }}
        docker_password: ${{ inputs.docker_password }}
        helm_user: ${{ inputs.helm_user }}
        helm_password: ${{ inputs.helm_password }}

    - name: Setup Google Cloud SDK apt keys
      shell: bash
      run: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: Apt Update
      shell: bash
      run: sudo apt-get update -y

    - name: Install gke-gcloud-auth-plugin
      shell: bash
      run: |
        sudo apt install -y \
        google-cloud-sdk-gke-gcloud-auth-plugin \
        kubectl

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Install kubectx
      shell: bash
      working-directory: /tmp
      run: |
        git clone https://github.com/ahmetb/kubectx
        echo "/tmp/kubectx" >> $GITHUB_PATH
