name: 'Cloud Dependencies Setup'
description: 'Installs the various cloud dependencies needed for the build and deploy workflows.'
inputs:
  repo_access_pat:
    description: 'GitHub Personal Access Token'
    required: true
    type: string
  docker_user:
    description: 'Docker Hub Username'
    required: true
    type: string
  docker_password:
    description: 'Docker Hub Password'
    required: true
    type: string
  helm_user:
    description: 'Harbor Registry Username'
    required: true
    type: string
  helm_password:
    description: 'Harbor Registry Password'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_user }}
        password: ${{ inputs.docker_password }}

    - name: Install Helm
      uses: Azure/setup-helm@v3

    - name: Log in to Harbor Registry
      shell: bash
      run: |
        echo '${{ inputs.helm_password }}' | helm registry login harbor.rutherford.patternlabs.tech -u '${{ inputs.helm_user }}' --password-stdin      

    - name: Setup .netrc
      uses: Pattern-Labs/.github/.github/actions/setup_netrc@main
      with:
        repo_access_pat: ${{ inputs.repo_access_pat }}

    - name: Setup Google Cloud SDK apt keys
      shell: bash
      run: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: Apt Update
      shell: bash
      run: sudo apt-get update -y

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4

    - name: Install gke-gcloud-auth-plugin
      shell: bash
      run: |
        sudo apt install -y \
        google-cloud-sdk-gke-gcloud-auth-plugin \
        kubectl

    - name: Install the Pattern CLI
      uses: Pattern-Labs/.github/.github/actions/pattern_cli@main

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true

    - name: Checkout kubectx
      uses: actions/checkout@v4
      with:
        repository: ahmetb/kubectx
        path: /opt/kubectx

    - name: Install kubectx
      shell: bash
      run: |
        sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
        sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens