name: "Pattern CLI Setup"
description: "Setup Pattern CLI"
inputs:
  add_to_usr_bin:
    description: "If true, copies the Pattern CLI to /usr/bin"
    required: false
    default: true
  version:
    description: "Pattern CLI version to install (e.g., v0.40.0, latest, or a branch name)"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Setup Go (branch build support)
      if: inputs.version != 'latest'
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Make sure .local/bin exists
      shell: bash
      run: mkdir -p ~/.local/bin

    - name: Download Pattern CLI
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ] || [ "$VERSION" = "latest" ]; then
          release_url="https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/latest"
        else
          release_url="https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/tags/${VERSION}"
        fi
        asset_url="$(curl -L -n -s "${release_url}" | jq -r '.assets[0].url // empty')"
        if [ -n "$asset_url" ]; then
          curl -L -n -H "Accept: application/octet-stream" -o ~/.local/bin/pattern "$asset_url"
          exit 0
        fi

        if ! command -v go >/dev/null 2>&1; then
          echo "Go is required to build Pattern CLI from ref '${VERSION}'." >&2
          exit 1
        fi

        echo "Building Pattern CLI from '${VERSION}'..."
        GOBIN=~/.local/bin GOPRIVATE=github.com/Pattern-Labs/* GONOSUMDB=github.com/Pattern-Labs/* \
          go install github.com/Pattern-Labs/pattern_cli/cmd/pattern@"${VERSION}"

    - name: Make Pattern CLI executable
      shell: bash
      run: chmod +x ~/.local/bin/pattern

    - name: Optionally add to /usr/bin
      if: inputs.add_to_usr_bin == 'true'
      shell: bash
      run: sudo cp ~/.local/bin/pattern /usr/bin/pattern

    - name: Test Pattern CLI
      shell: bash
      run: pattern version
