name: 'Pattern CLI Setup'
description: 'Setup Pattern CLI'
runs:
  using: "composite"
  steps:
    - name: Make sure .local/bin exists
      shell: bash    
      run: mkdir -p ~/.local/bin

    - name: Download Pattern CLI
      shell: bash
      run: curl -L -n -H "Accept: application/octet-stream" -o ~/.local/bin/pattern `curl -L -n https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/latest | jq -r .assets[0].url`

    - name: Make Pattern CLI executable
      shell: bash
      run: chmod +x ~/.local/bin/pattern

    - name: Test Pattern CLI
      shell: bash 
      run: pattern version
