name: 'Pattern CLI Setup'
description: 'Setup Pattern CLI'
runs:
  using: "composite"
  steps:
    - name: Install the Pattern CLI
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        curl -L -n -H "Accept: application/octet-stream" -o ~/.local/bin/pattern `curl -L -n https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/latest | jq -r .assets[0].url`
        chmod +x ~/.local/bin/pattern

    - name: Test Pattern CLI
      shell: bash 
      run: pattern version

    - name: Initialize Clusters
      shell: bash
      run: pattern clusters init