name: 'Pattern CLI Setup'
description: 'Setup Pattern CLI'
inputs:
  repo_access_pat:
    description: 'GitHub Personal Access Token'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout dev-containers repo
      uses: actions/checkout@v3
      with:
        repository: Pattern-Labs/dev-containers
        token: ${{ inputs.repo_access_pat }}
        path: dev-containers
        ref: main

    - name: Install the Pattern CLI
      run: |
        cd dev-containers
        sudo env_modules/99-google_cloud.sh
        ./install_pattern_cli.sh
        ./setup_host.sh -q

    - name: Test Pattern CLI
      shell: bash 
      run: pattern version

    - name: Initialize Clusters
      shell: bash
      run: pattern clusters init      