name: "Pattern CLI Setup"
description: "Setup Pattern CLI"
inputs:
  add_to_usr_bin:
    description: "If true, copies the Pattern CLI to /usr/bin"
    required: false
    default: true
  version:
    description: "Pattern CLI version to install (e.g., v0.40.0 or latest)"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Make sure .local/bin exists
      shell: bash
      run: mkdir -p ~/.local/bin

    - name: Download Pattern CLI
      shell: bash
      run: |
        if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "latest" ]; then
          release_url="https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/latest"
        else
          release_url="https://api.github.com/repos/Pattern-Labs/pattern_cli/releases/tags/${{ inputs.version }}"
        fi
        url="$(curl -L -n "${release_url}" | jq -r .assets[0].url)"
        curl -L -n -H "Accept: application/octet-stream" -o ~/.local/bin/pattern "$url"

    - name: Make Pattern CLI executable
      shell: bash
      run: chmod +x ~/.local/bin/pattern

    - name: Optionally add to /usr/bin
      if: inputs.add_to_usr_bin == 'true'
      shell: bash
      run: sudo cp ~/.local/bin/pattern /usr/bin/pattern

    - name: Test Pattern CLI
      shell: bash
      run: pattern version
