name: Deploy Molecule

on:
  workflow_call:
    inputs:
      namespace:
        description: namespace to deploy chart to
        required: true
        type: string
      molecule_path:
        description: path to molecule to deploy
        required: true
        type: string
      chart_name:
        description: name of the chart to deploy
        required: true
        type: string
      tag:
        description: tag to tag built images with
        required: true
        type: string
      deployment_name:
        description: optional deployment name
        required: false
        type: string
      helm_flags:
        description: helm flags to pass to the command
        required: false
        type: string
      cluster_name:
        description: name of the cluster to deploy to
        required: false
        default: "rutherford"
        type: string

jobs:
  deploy-molecule:
    name: Deploy ${{ inputs.molecule_path }} ${{ inputs.chart_name }}
    runs-on: [github-hosted-cloud-builder]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Cloud Deps
        uses: Pattern-Labs/.github/.github/actions/setup_cloud_deps@main
        with:
          repo_access_pat: ${{ secrets.REPO_ACCESS_PAT }}
          docker_user: ${{ secrets.DOCKER_USER }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          helm_user: ${{ secrets.HELM_USER }}
          helm_password: ${{ secrets.HELM_PASSWORD }}

      - name: Establish Google Cloud Auth
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "stalwart-summer-374519"
          workload_identity_provider: "projects/515604670361/locations/global/workloadIdentityPools/github/providers/pattern"
          service_account: "github-runner@stalwart-summer-374519.iam.gserviceaccount.com"

      - name: Pattern Clusters Init
        run: pattern clusters init

      - name: Pattern Clusters Init Secrets
        run: pattern clusters init secrets

      - name: Switch to the right cluster
        run: kubectx ${{ inputs.cluster_name }}

      - name: Switch to the right namespace
        run: kubens ${{ inputs.namespace }}

      - name: Deploy Molecule
        run: |
          cd ${{ inputs.molecule_path }}

          # DEPLOY CMD
          COMMAND="pattern molecule deploy ${{ inputs.chart_name }} -t ${{ inputs.tag }}"

          # Check if deployment_name is set is set
          if [ -n "${{ inputs.deployment_name }}" ]; then
            COMMAND="$COMMAND -n ${{ inputs.deployment_name }}"
          fi
          # Check if helm flags is set
          if [ -n "${{ inputs.helm_flags }}" ]; then
            COMMAND="$COMMAND -- ${{ inputs.helm_flags }}"
          fi
          # Run Deploy
          $COMMAND
