name: Deploy Molecule

on:
  workflow_call:
    inputs:
      namespace:
        description: namespace to deploy chart to
        required: true
        type: string
      molecule_path:
        description: path to molecule to deploy
        required: true
        type: string
      chart_name:
        description: name of the chart to deploy
        required: true
        type: string
      tag:
        description: tag to tag built images with
        required: true
        type: string
      deployment_name:
        description: optional deployment name
        required: false
        type: string
      helm_flags:
        description: helm flags to pass to the command
        required: false
        type: string
      cluster_name:
        description: name of the cluster to deploy to
        required: false
        default: "rutherford"
        type: string

jobs:
  deploy-molecule:
    name: Deploy ${{ inputs.molecule_path }} ${{ inputs.chart_name }}
    runs-on: [github-hosted-cloud-builder]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Helm
        uses: Azure/setup-helm@v3

      - name: Log in to Harbor Registry
        run: |
          echo '${{ secrets.HELM_PASSWORD }}' | helm registry login harbor.rutherford.patternlabs.tech -u '${{ secrets.HELM_USER }}' --password-stdin

      - name: Setup .netrc
        uses: Pattern-Labs/.github/.github/actions/setup_netrc@main
        with:
          repo_access_pat: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Establish Google Cloud Auth
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "stalwart-summer-374519"
          workload_identity_provider: "projects/515604670361/locations/global/workloadIdentityPools/github/providers/pattern"
          service_account: "github-runner@stalwart-summer-374519.iam.gserviceaccount.com"

      - name: Install
        run: sudo apt install google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Install the Pattern CLI
        uses: Pattern-Labs/.github/.github/actions/pattern_cli@main

      - name: Pattern Clusters Init
        run: pattern clusters init

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true

      - name: Switch to the right cluster
        run: kubectx ${{ inputs.cluster_name }}

      - name: Switch to the right namespace
        run: kubens ${{ inputs.namespace }}

      - name: Deploy Molecule
        run: |
          cd ${{ inputs.molecule_path }}

          # DEPLOY CMD
          COMMAND="pattern molecule deploy ${{ inputs.chart_name }} -t ${{ inputs.tag }}"

          # Check if deployment_name is set is set
          if [ -n "${{ inputs.deployment_name }}" ]; then
            COMMAND="$COMMAND -n ${{ inputs.deployment_name }}"
          fi
          # Check if helm flags is set
          if [ -n "${{ inputs.helm_flags }}" ]; then
            COMMAND="$COMMAND -- ${{ inputs.helm_flags }}"
          fi
          # Run Deploy
          $COMMAND
